# -*- coding: utf-8 -*-
"""DataPrep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AC3KWzN-2Nw6aBe6uugOWOdWFHBmRiOv
"""

#!pip install ProgressBar2
#import ProgressBar2 

import sys
import os
import time
import hashlib
import struct
import subprocess
import collections
import tensorflow as tf
from tensorflow.core.example import example_pb2
import nltk
#nltk.download('punkt')
from nltk.tokenize import word_tokenize
import pandas as pd

dm_single_close_quote = u'\u2019' # unicode
dm_double_close_quote = u'\u201d'
END_TOKENS = ['.', '!', '?', '...', "'", "`", '"', dm_single_close_quote, dm_double_close_quote, ")"] # acceptable ways to end a sentence

# We use these to separate the summary sentences in the .bin datafiles
SENTENCE_START = '<s>'
SENTENCE_END = '</s>'

all_train_urls = ""
all_val_urls = ""
all_test_urls = ""

#def_path="drive/My Drive/Diplomatiki_sum/DataPrep/"
tokenized_data_dir ="data_tokenized_v2" #location of folder to tokenize text
#dm_tokenized_stories_dir = def_path+"dm_stories_tokenized" #not used
finished_files_dir ="greek_finished_files_v2" #final ouput
chunks_dir = os.path.join(finished_files_dir, "chunked")



VOCAB_SIZE = 200000 #maybe this is big and i dont need to define it
CHUNK_SIZE = 1000 # num examples per chunk, for the chunked data

import re
#Clean final data
def final_clean(raw_text):
    #Remove non Greek words
    text=re.sub("[a-zA-Z]",'',raw_text)
    #Remove numbers ?
    text=re.sub("[0-9]",'',text)
    #Remove text in parenthesis 
    text=re.sub(r'\([^)]*\)', '', text)
    #Remove special characters 
    text=re.sub("[\\\]",' ',text)
    text=re.sub("[\^\\/\{\}\[\]!%__@#$&\*\-_<>–?:\"\.<>”“+=:;\,«»…]",'',text)
    text=re.sub(r'\’','',text)
    text=re.sub(r'\'','',text)
    #Remove multiple spaces
    text = re.sub("(\s+)",' ',text)
    text = re.sub("(\t)",'',text)
    return text

def chunk_file(set_name):
  in_file = finished_files_dir + '/%s.bin' % set_name
  reader = open(in_file, "rb")
  chunk = 0
  finished = False
  while not finished:
    chunk_fname = os.path.join(chunks_dir, '%s_%03d.bin' % (set_name, chunk)) # new chunk
    with open(chunk_fname, 'wb') as writer:
      for _ in range(CHUNK_SIZE):
        len_bytes = reader.read(8)
        if not len_bytes:
          finished = True
          break
        str_len = struct.unpack('q', len_bytes)[0]
        example_str = struct.unpack('%ds' % str_len, reader.read(str_len))[0]
        writer.write(struct.pack('q', str_len))
        writer.write(struct.pack('%ds' % str_len, example_str))
      chunk += 1


def chunk_all():
  # Make a dir to hold the chunks
  if not os.path.isdir(chunks_dir):
    os.mkdir(chunks_dir)
  # Chunk the data
  for set_name in ['train', 'val', 'test']:
    print ("Splitting %s data into chunks..." % set_name)
    chunk_file(set_name)
  print ("Saved chunked data in %s" % chunks_dir)

def tokenize_data(reviews, tokenized_data_dir):
  """Maps a whole directory of .story files to a tokenized version using Stanford CoreNLP Tokenizer"""
  #progress = ProgressBar.ProgressBar(len(reviews), fmt=ProgressBar.ProgressBar.FULL)
  for i, row in reviews.iterrows():
        #if i==20:
        #    break
        filename = str(i) + '.tok'
        with open(os.path.join(tokenized_data_dir, filename), 'w', encoding="utf-8") as temp_file:
            text = row["Text"]
            #print(text)
            text = final_clean(text)
            #print(text)
            tok = nltk.word_tokenize(text)
            tok.append("@highlight")
            #print(tok)
            Summary = row["Summary"]
            Summary = final_clean(Summary)
            tok.extend(nltk.word_tokenize(Summary))
            #print(tok)
            list = tok.copy()

            for i in tok:
                if(i=='``' or i=="''" ):
                    list.remove(i)
            tok_string = "\n".join(str(x) for x in list)
            #print(tok_string)
            temp_file.write(tok_string)

        #progress.current += 1
        #progress()
  print ("Successfully finished tokenizing to %s .\n" % (tokenized_data_dir))

def fix_missing_period(line):
  """Adds a period to a line that is missing a period"""
  if "@highlight" in line: return line
  if line=="": return line
  if line[-1] in END_TOKENS: return line
  # print line[-1]
  return line

def read_text_file(text_file):
  lines = []
  with open(text_file, "r", encoding="utf-8") as f:
    for line in f:
      lines.append(line.strip())
  return lines

def get_art_abs(story_file):
  lines = read_text_file(story_file)

  # Lowercase everything
  lines = [line.lower() for line in lines]

  # Put periods on the ends of lines that are missing them (this is a problem in the dataset because many image captions don't end in periods; consequently they end up in the body of the article as run-on sentences)
  lines = [fix_missing_period(line) for line in lines]
  #print(lines)

  # Separate out article and abstract sentences
  article_lines = []
  highlights = []
  next_is_highlight = False
  for idx,line in enumerate(lines):
    if line == "":
      continue # empty line
    elif line.startswith("@highlight"):
      next_is_highlight = True
    elif next_is_highlight:
      highlights.append(line)
    else:
      article_lines.append(line)

  # Make article into a single string
  article = ' '.join(article_lines)
  #print(article)

  # Make abstract into a signle string, putting <s> and </s> tags around the sentences
  abstract = ' '.join(["%s %s %s" % (SENTENCE_START, sent, SENTENCE_END) for sent in highlights])
  #print(abstract)
  return article, abstract


def write_to_bin(file_names, out_file, makevocab=True):
  """Reads the tokenized .story files corresponding to the urls listed in the url_file and writes them to a out_file."""
  story_fnames = [str(s)+".tok" for s in file_names]
  num_stories = len(story_fnames)
  if makevocab:
    vocab_counter = collections.Counter()
  with open(out_file, 'wb') as writer:
    for idx,s in enumerate(story_fnames):
      if idx % 1000 == 0:
        print( "Writing story %i of %i; %.2f percent done" % (idx, num_stories, float(idx)*100.0/float(num_stories)))
      # Look in the tokenized story dirs to find the .story file corresponding to this url
      if os.path.isfile(os.path.join(tokenized_data_dir, s)):
        story_file = os.path.join(tokenized_data_dir, s)
      elif os.path.isfile(os.path.join(dm_tokenized_stories_dir, s)):
        story_file = os.path.join(dm_tokenized_stories_dir, s)
      else:
        print ("Error: Couldn't find tokenized story file %s in either tokenized story directories %s and %s. Was there an error during tokenization?" % (s, tokenized_data_dir, dm_tokenized_stories_dir))
        # Check again if tokenized stories directories contain correct number of files
        print ("Checking that the tokenized stories directories %s and %s contain correct number of files..." % (tokenized_data_dir, dm_tokenized_stories_dir))
        #check_num_stories(cnn_tokenized_stories_dir, num_expected_cnn_stories)
        #check_num_stories(dm_tokenized_stories_dir, num_expected_dm_stories)
        #raise Exception("Tokenized stories directories %s and %s contain correct number of files but story file %s found in neither." % (cnn_tokenized_stories_dir, dm_tokenized_stories_dir, s))   
      # Get the strings to write to .bin file
      article, abstract = get_art_abs(story_file) 
      # Write to tf.Example
      tf_example = example_pb2.Example()
      tf_example.features.feature['article'].bytes_list.value.extend([article.encode('utf-8')])
      tf_example.features.feature['abstract'].bytes_list.value.extend([abstract.encode('utf-8')])
      tf_example_str = tf_example.SerializeToString()
      str_len = len(tf_example_str)
      writer.write(struct.pack('q', str_len))
      writer.write(struct.pack('%ds' % str_len, tf_example_str))
      # Write the vocab to file, if applicable
      if makevocab:
        art_tokens = article.split(' ')
        abs_tokens = abstract.split(' ')
        abs_tokens = [t for t in abs_tokens if t not in [SENTENCE_START, SENTENCE_END]] # remove these tags from vocab
        tokens = art_tokens + abs_tokens
        tokens = [t.strip() for t in tokens] # strip
        tokens = [t for t in tokens if t!=""] # remove empty
        vocab_counter.update(tokens)
  print ("Finished writing file %s\n" % out_file)
  # write vocab to file
  if makevocab:
    print ("Writing vocab file...")
    with open(os.path.join(finished_files_dir, "vocab"), 'w', encoding="utf-8") as writer:
      #for word, count in vocab_counter.most_common(VOCAB_SIZE):
      for word, count in vocab_counter.most_common():
        writer.write(word + ' ' + str(count) + '\n')
    print ("Finished writing vocab file")


def check_num_stories(stories_dir, num_expected):
  num_stories = len(os.listdir(stories_dir))
  if num_stories != num_expected:
    raise Exception("stories directory %s contains %i files but should contain %i" % (stories_dir, num_stories, num_expected))

if __name__ == '__main__':

  start_time=time.time()
  #main directory
  #data_dir =  "drive/My Drive/Diplomatiki_sum/Data/"

  # Create some new directories
  if not os.path.exists(tokenized_data_dir): os.makedirs(tokenized_data_dir)
  if not os.path.exists(finished_files_dir): os.makedirs(finished_files_dir)

  #data needed is in a csv format
  #containg 2 columbs (content , title)
  reviews_csv ="clean_greek_data_final_v2.csv"
  reviews = pd.read_csv(reviews_csv,skiprows=[1],skip_blank_lines=True)
  reviews = reviews.filter(['Text','Summary'])
  reviews = reviews.dropna()
  reviews = reviews.reset_index(drop=True)
  reviews.head()

  # Run nltk tokenizer on both text and summary , outputting to tokenized stories directories
  tokenize_data(reviews, tokenized_data_dir)

  #to get the length of your dataset
  num_expected_data =reviews.shape[0]
  print(num_expected_data)

  #training data = all_data-2000
  #testing data = 1000
  #validation data = 1000
  all_train_urls = range(0,num_expected_data-6000)
  all_val_urls = range(num_expected_data-6000,num_expected_data-1000)
  all_test_urls = range(num_expected_data-1000,num_expected_data)

  #for testing
  ##############all_train_urls= range(0,80)
  ##############all_val_urls = range(80,90)
  ##############all_test_urls = range(90,100)

  # Read the tokenized stories, do a little postprocessing then write to bin files
  write_to_bin(all_test_urls, os.path.join(finished_files_dir, "test.bin"))
  write_to_bin(all_val_urls, os.path.join(finished_files_dir, "val.bin"))
  write_to_bin(all_train_urls, os.path.join(finished_files_dir, "train.bin"), makevocab=True)

  # Chunk the data. This splits each of train.bin, val.bin and test.bin into smaller chunks, each containing e.g. 1000 examples, and saves them in finished_files/chunks
  chunk_all()
   
  print("--- %s seconds ---" % (time.time() - start_time))
